# Generated by Django 5.0.6 on 2024-06-30 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=200, null=True, verbose_name='Регион')),
                ('number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер АЗС')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Долгота')),
                ('related_service', models.TextField(blank=True, null=True, verbose_name='Сопутствующий сервис')),
                ('additional_service', models.TextField(blank=True, null=True, verbose_name='Дополнительные услуги')),
                ('diesel_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена ДТ')),
                ('taneko_diesel_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена ДТ ТАНЕКО')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'АЗС',
                'verbose_name_plural': 'АЗС',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=255, verbose_name='координаты отправки')),
                ('end_point', models.CharField(max_length=255, verbose_name='координаты прибытия')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='высота от земли(метры)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='вес авто(тонны)')),
                ('axel_load', models.FloatField(blank=True, null=True, verbose_name='нагрузка на ось(тонны)')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'маршрут',
                'verbose_name_plural': 'маршруты',
            },
        ),
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.gasstation', verbose_name='АЗС')),
            ],
            options={
                'verbose_name': 'Заправка на маршруте',
                'verbose_name_plural': 'Заправки на маршрутах',
            },
        ),
    ]
