# Generated by Django 5.0.6 on 2024-07-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='название'),
        ),
    ]
