# Generated by Django 5.0.6 on 2024-07-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_route_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasstation',
            name='elevation',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='высота над уровнем моря'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='маршрут'),
        ),
    ]
